// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRteLUZ5zEhm7j1HjwF1hsSKSNYZ6v_Y',
    appId: '1:773169716410:web:31855918e65acf53e43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    authDomain: 'beachbook-163923.firebaseapp.com',
    storageBucket: 'beachbook-163923.appspot.com',
    measurementId: 'G-CR7ZEVY3ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_8OJxojdL1DjsEuBJNTBT6KWBobmi7g',
    appId: '1:773169716410:android:e6bedafb2c7fc0dfe43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRIewWfdUMUlvVzikrknXih_cba4f7X0',
    appId: '1:773169716410:ios:f250bbb121a444b3e43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
    androidClientId: '773169716410-h173k2osuv20nmnmhtoh2cs64sqfv2c1.apps.googleusercontent.com',
    iosClientId: '773169716410-du7ei7t0ktgu7ov5ket0ggbo73a5bnmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybeachbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRIewWfdUMUlvVzikrknXih_cba4f7X0',
    appId: '1:773169716410:ios:f250bbb121a444b3e43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
    androidClientId: '773169716410-h173k2osuv20nmnmhtoh2cs64sqfv2c1.apps.googleusercontent.com',
    iosClientId: '773169716410-du7ei7t0ktgu7ov5ket0ggbo73a5bnmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybeachbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkULKwQZeUl4SbZxNdfxPxLGO-AvMjZo4',
    appId: '1:773169716410:web:46bc54460d4f0d2ae43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    authDomain: 'beachbook-163923.firebaseapp.com',
    storageBucket: 'beachbook-163923.appspot.com',
    measurementId: 'G-V93NFW6QXV',
  );
}